In [1]:
rand(3,2)

NameError: name 'rand' is not defined

In [ ]:
randome.rand(3)

NameError: name 'randome' is not defined

In [ ]:
import numpy as np
import random   
np.random.rand(3)

array([0.44338457, 0.46247618, 0.15615744])

In [ ]:
np.random.rand(1,1)

array([[0.20726495]])

In [ ]:
np.random.rand(3,2)

array([[0.03723464, 0.38484489],
       [0.45521256, 0.41014593],
       [0.65190338, 0.23753179]])

In [ ]:
np.random.randint(3)

0

In [ ]:
np.random.randint(2,15)

4

In [ ]:
np.random.randint(2,10,4)

array([8, 5, 9, 7], dtype=int32)

In [ ]:
np.random.randint(-30,20,10)

array([-14,  -6,  15,  15, -19,   8, -13,  -2,  14,  -1], dtype=int32)

In [ ]:
np.random.randint(10,40,(5,5))

array([[32, 14, 35, 19, 22],
       [21, 12, 35, 36, 26],
       [39, 22, 37, 19, 25],
       [17, 28, 11, 23, 11],
       [14, 35, 24, 28, 35]], dtype=int32)

In [ ]:
np.random.randint(10,100,(9,9))

array([[71, 75, 64, 58, 61, 30, 70, 95, 45],
       [32, 65, 13, 58, 18, 52, 79, 10, 36],
       [61, 70, 34, 21, 87, 38, 80, 66, 19],
       [26, 42, 42, 50, 38, 85, 91, 50, 77],
       [42, 86, 78, 60, 99, 92, 28, 88, 85],
       [93, 87, 45, 50, 24, 71, 53, 29, 89],
       [26, 21, 64, 14, 78, 27, 17, 59, 53],
       [13, 13, 48, 49, 32, 78, 51, 33, 47],
       [82, 23, 83, 77, 16, 80, 26, 36, 94]], dtype=int32)

In [ ]:
ml=[0,1,2,3,4,5]
ml

[0, 1, 2, 3, 4, 5]

In [ ]:
arr=np.array(ml)
arr

array([0, 1, 2, 3, 4, 5])

In [ ]:
arr.reshape(2,3)


array([[0, 1, 2],
       [3, 4, 5]])

In [ ]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [ ]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [ ]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [ ]:
n=  np.random.randint(10,20,(4,4))
n

array([[12, 18, 11, 15],
       [17, 13, 14, 10],
       [12, 18, 16, 14],
       [14, 18, 12, 18]], dtype=int32)

In [ ]:
n=  np.random.randint(10,50,(6,6))
n

array([[25, 23, 29, 18, 41, 21],
       [49, 33, 27, 25, 13, 28],
       [20, 47, 28, 13, 13, 34],
       [34, 15, 40, 44, 28, 46],
       [11, 17, 49, 38, 37, 43],
       [30, 17, 18, 47, 13, 20]], dtype=int32)

In [ ]:
n[:]

array([[25, 23, 29, 18, 41, 21],
       [49, 33, 27, 25, 13, 28],
       [20, 47, 28, 13, 13, 34],
       [34, 15, 40, 44, 28, 46],
       [11, 17, 49, 38, 37, 43],
       [30, 17, 18, 47, 13, 20]], dtype=int32)

In [ ]:
n[1:6]

array([[49, 33, 27, 25, 13, 28],
       [20, 47, 28, 13, 13, 34],
       [34, 15, 40, 44, 28, 46],
       [11, 17, 49, 38, 37, 43],
       [30, 17, 18, 47, 13, 20]], dtype=int32)

In [ ]:
import numpy as np
import random   
n1=np.random.randint(10,50,(8,8))   
n1

array([[17, 15, 22, 17, 38, 11, 40, 18],
       [14, 43, 39, 36, 44, 39, 43, 27],
       [32, 31, 41, 13, 43, 11, 29, 39],
       [43, 40, 38, 12, 30, 41, 18, 14],
       [15, 34, 27, 31, 27, 29, 39, 28],
       [28, 32, 23, 40, 37, 36, 10, 18],
       [46, 23, 10, 21, 29, 10, 43, 48],
       [41, 28, 41, 36, 35, 46, 34, 21]], dtype=int32)

In [ ]:
n1[:]

array([[17, 15, 22, 17, 38, 11, 40, 18],
       [14, 43, 39, 36, 44, 39, 43, 27],
       [32, 31, 41, 13, 43, 11, 29, 39],
       [43, 40, 38, 12, 30, 41, 18, 14],
       [15, 34, 27, 31, 27, 29, 39, 28],
       [28, 32, 23, 40, 37, 36, 10, 18],
       [46, 23, 10, 21, 29, 10, 43, 48],
       [41, 28, 41, 36, 35, 46, 34, 21]], dtype=int32)

In [ ]:
n1[1:3]

array([[14, 43, 39, 36, 44, 39, 43, 27],
       [32, 31, 41, 13, 43, 11, 29, 39]], dtype=int32)

In [ ]:
n1[-1:]


array([[41, 28, 41, 36, 35, 46, 34, 21]], dtype=int32)

In [ ]:
n1[:]

array([[17, 15, 22, 17, 38, 11, 40, 18],
       [14, 43, 39, 36, 44, 39, 43, 27],
       [32, 31, 41, 13, 43, 11, 29, 39],
       [43, 40, 38, 12, 30, 41, 18, 14],
       [15, 34, 27, 31, 27, 29, 39, 28],
       [28, 32, 23, 40, 37, 36, 10, 18],
       [46, 23, 10, 21, 29, 10, 43, 48],
       [41, 28, 41, 36, 35, 46, 34, 21]], dtype=int32)

In [ ]:
n1[:-1]

array([[17, 15, 22, 17, 38, 11, 40, 18],
       [14, 43, 39, 36, 44, 39, 43, 27],
       [32, 31, 41, 13, 43, 11, 29, 39],
       [43, 40, 38, 12, 30, 41, 18, 14],
       [15, 34, 27, 31, 27, 29, 39, 28],
       [28, 32, 23, 40, 37, 36, 10, 18],
       [46, 23, 10, 21, 29, 10, 43, 48]], dtype=int32)

In [ ]:
n1[-2:]

array([[46, 23, 10, 21, 29, 10, 43, 48],
       [41, 28, 41, 36, 35, 46, 34, 21]], dtype=int32)

In [ ]:
n1[1,3]

np.int32(36)

In [ ]:
n1[1,-1]

np.int32(27)

In [ ]:
import numpy as np
import random   
m= np.random.randint(0,100,(5,5))
m

array([[73, 22, 64, 23, 71],
       [86, 61, 88, 93, 91],
       [88, 30,  9, 28, 26],
       [54, 99,  5, 49, 76],
       [47, 83, 60, 63, 61]], dtype=int32)

In [ ]:
row =3
col=2
m[row,col]

np.int32(5)

In [ ]:
m[1]

array([86, 61, 88, 93, 91], dtype=int32)

In [ ]:
m[:,col]

array([64, 88,  9,  5, 60], dtype=int32)

In [ ]:
m[:,3]

array([23, 93, 28, 49, 63], dtype=int32)

In [ ]:
m[3]

array([54, 99,  5, 49, 76], dtype=int32)

In [6]:
import numpy as np
n=  np.random.randint(0,100,(5,5))
n

array([[84, 53,  8, 18, 87],
       [52, 72, 53, 25, 60],
       [10, 90, 26, 24, 94],
       [42, 22, 43, 11, 59],
       [43, 92, 54, 16, 84]], dtype=int32)

In [7]:
n[::-1]

array([[43, 92, 54, 16, 84],
       [42, 22, 43, 11, 59],
       [10, 90, 26, 24, 94],
       [52, 72, 53, 25, 60],
       [84, 53,  8, 18, 87]], dtype=int32)

In [8]:
n[::-2]

array([[43, 92, 54, 16, 84],
       [10, 90, 26, 24, 94],
       [84, 53,  8, 18, 87]], dtype=int32)

In [9]:
n[1:5,2:4]

array([[53, 25],
       [26, 24],
       [43, 11],
       [54, 16]], dtype=int32)

In [10]:
n[:]

array([[84, 53,  8, 18, 87],
       [52, 72, 53, 25, 60],
       [10, 90, 26, 24, 94],
       [42, 22, 43, 11, 59],
       [43, 92, 54, 16, 84]], dtype=int32)

In [11]:
n[0:3,3:5]

array([[18, 87],
       [25, 60],
       [24, 94]], dtype=int32)

In [12]:
n[n>50]

array([84, 53, 87, 52, 72, 53, 60, 90, 94, 59, 92, 54, 84], dtype=int32)

In [13]:
n[n<50]

array([ 8, 18, 25, 10, 26, 24, 42, 22, 43, 11, 43, 16], dtype=int32)

In [14]:
n[n!=50]

array([84, 53,  8, 18, 87, 52, 72, 53, 25, 60, 10, 90, 26, 24, 94, 42, 22,
       43, 11, 59, 43, 92, 54, 16, 84], dtype=int32)