In [1]:
rand(3,2)

NameError: name 'rand' is not defined

In [2]:
randome.rand(3)

NameError: name 'randome' is not defined

In [4]:
import numpy as np
import random   
np.random.rand(3)

array([0.44338457, 0.46247618, 0.15615744])

In [5]:
np.random.rand(1,1)

array([[0.20726495]])

In [6]:
np.random.rand(3,2)

array([[0.03723464, 0.38484489],
       [0.45521256, 0.41014593],
       [0.65190338, 0.23753179]])

In [9]:
np.random.randint(3)

0

In [10]:
np.random.randint(2,15)

4

In [11]:
np.random.randint(2,10,4)

array([8, 5, 9, 7], dtype=int32)

In [12]:
np.random.randint(-30,20,10)

array([-14,  -6,  15,  15, -19,   8, -13,  -2,  14,  -1], dtype=int32)

In [13]:
np.random.randint(10,40,(5,5))

array([[32, 14, 35, 19, 22],
       [21, 12, 35, 36, 26],
       [39, 22, 37, 19, 25],
       [17, 28, 11, 23, 11],
       [14, 35, 24, 28, 35]], dtype=int32)

In [14]:
np.random.randint(10,100,(9,9))

array([[71, 75, 64, 58, 61, 30, 70, 95, 45],
       [32, 65, 13, 58, 18, 52, 79, 10, 36],
       [61, 70, 34, 21, 87, 38, 80, 66, 19],
       [26, 42, 42, 50, 38, 85, 91, 50, 77],
       [42, 86, 78, 60, 99, 92, 28, 88, 85],
       [93, 87, 45, 50, 24, 71, 53, 29, 89],
       [26, 21, 64, 14, 78, 27, 17, 59, 53],
       [13, 13, 48, 49, 32, 78, 51, 33, 47],
       [82, 23, 83, 77, 16, 80, 26, 36, 94]], dtype=int32)

In [16]:
ml=[0,1,2,3,4,5]
ml

[0, 1, 2, 3, 4, 5]

In [17]:
arr=np.array(ml)
arr

array([0, 1, 2, 3, 4, 5])

In [18]:
arr.reshape(2,3)


array([[0, 1, 2],
       [3, 4, 5]])

In [19]:
arr.reshape(3,2)

array([[0, 1],
       [2, 3],
       [4, 5]])

In [20]:
arr.reshape(3,3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [21]:
arr.reshape(6,1)

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5]])

In [33]:
n=  np.random.randint(10,20,(4,4))
n

array([[12, 18, 11, 15],
       [17, 13, 14, 10],
       [12, 18, 16, 14],
       [14, 18, 12, 18]], dtype=int32)

In [34]:
n=  np.random.randint(10,50,(6,6))
n

array([[25, 23, 29, 18, 41, 21],
       [49, 33, 27, 25, 13, 28],
       [20, 47, 28, 13, 13, 34],
       [34, 15, 40, 44, 28, 46],
       [11, 17, 49, 38, 37, 43],
       [30, 17, 18, 47, 13, 20]], dtype=int32)

In [35]:
n[:]

array([[25, 23, 29, 18, 41, 21],
       [49, 33, 27, 25, 13, 28],
       [20, 47, 28, 13, 13, 34],
       [34, 15, 40, 44, 28, 46],
       [11, 17, 49, 38, 37, 43],
       [30, 17, 18, 47, 13, 20]], dtype=int32)

In [37]:
n[1:6]

array([[49, 33, 27, 25, 13, 28],
       [20, 47, 28, 13, 13, 34],
       [34, 15, 40, 44, 28, 46],
       [11, 17, 49, 38, 37, 43],
       [30, 17, 18, 47, 13, 20]], dtype=int32)