In [26]:
import numpy as np
np.__version__

'2.3.0'

In [27]:
ml=[0,1,2,3,4,5]
ml

[0, 1, 2, 3, 4, 5]

In [28]:
type(ml)

list

In [29]:
arr=np.array(ml)
arr

array([0, 1, 2, 3, 4, 5])

In [30]:
type(arr)

numpy.ndarray

In [31]:
print(type(arr))
print(type(ml))

<class 'numpy.ndarray'>
<class 'list'>


In [32]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [33]:
np.arange(10,20)

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [34]:
np.arange(10, 20, 2)

array([10, 12, 14, 16, 18])

In [35]:
np.arange(10,20,3,4)

TypeError: Cannot interpret '4' as a data type

In [ ]:
np.arange(10,5)

array([], dtype=int64)

In [ ]:
np.arange(-20,8)

array([-20, -19, -18, -17, -16, -15, -14, -13, -12, -11, -10,  -9,  -8,
        -7,  -6,  -5,  -4,  -3,  -2,  -1,   0,   1,   2,   3,   4,   5,
         6,   7])

In [ ]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [ ]:
np.zeros(5,dtype=int)

array([0, 0, 0, 0, 0])

In [ ]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
np.zeros((4,4),dtype=int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0]])

In [ ]:
print(np.ones(5))
print(np.ones(5, dtype=int))

[1. 1. 1. 1. 1.]
[1 1 1 1 1]


In [ ]:
np.ones((3,3), dtype=int)

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

In [ ]:
np.ones((10,10), dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])